tests:
  image: python:3.11
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install -U pip
    - pip install flake8 mypy coverage pytest interrogate scipy
    - pip install --no-deps git+https://gitlab.com/ase/ase.git
    - pip install .
    - coverage run --source=cxdb -m pytest -v --color=yes
    - coverage report -i --precision=2 --fail-under=20
    - coverage html
    - mypy -p cxdb
    - flake8 cxdb
    - interrogate -v -m -i -f 2.8 cxdb -e cxdb/test
  coverage: '/TOTAL +[0-9]+ +[0-9]+ +([0-9]+\.[0-9]+%)/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week
