tests:
  image: python:3.12
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install -U pip
    - pip install flake8 mypy coverage pytest scipy click boddle
    - pip install --no-deps git+https://gitlab.com/ase/ase.git
    - pip install --no-deps git+https://gitlab.com/asr-dev/asr.git
    - pip install .
    - coverage run --branch -m pytest -v -We --color=yes
    - coverage report -i --precision=2 --fail-under=99.5
    - coverage html
    - mypy
    - flake8 cxdb
  coverage: '/TOTAL +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +([0-9]+\.[0-9]+%)/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week
