variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"


cache:
  paths:
    - $PIP_CACHE_DIR
    - $CI_PROJECT_DIR/venv
  key: $CI_PROJECT_ID


tests:
  image: python:3.12
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install -U pip
    - pip install git+https://gitlab.com/ase/ase.git
    - pip install git+https://gitlab.com/asr-dev/asr.git
    - pip install .[test,optimade]
    - coverage run --branch -m pytest -v --color=yes --junit-xml=junit.xml
    - coverage report -i --precision=2 --skip-covered --sort=miss
    - coverage html --skip-covered
    - coverage xml --data-file .coverage
    - mypy
    - flake8 camdweb
  coverage: '/TOTAL +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +([0-9]+\.[0-9]+%)/'
  artifacts:
    paths:
      - htmlcov
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml
    expire_in: 1 week


oldtests:
  image: python:3.10
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install -U pip
    - pip install git+https://gitlab.com/ase/ase.git
    - pip install git+https://gitlab.com/asr-dev/asr.git
    - pip install pytest boddle
    - pip install .
    - pytest -v --color=yes
  when: manual


monitoring:
  image: python:3.12
  script:
    - python camdweb/monitor.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
