tests:
  image: python:3.12
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install -U pip
    - pip install git+https://gitlab.com/ase/ase
    - pip install git+https://gitlab.com/asr-dev/asr
    - pip install .[test]
    - coverage run --branch -m pytest -v --color=yes
    - coverage report -i --precision=2 --fail-under=99.5
    - coverage html
    - mypy
    - flake8 camdweb
  coverage: '/TOTAL +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +([0-9]+\.[0-9]+%)/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week

oldtests:
  image: python:3.9
  script:
    - python -m venv venv
    - . venv/bin/activate
    - pip install -U pip
    - pip install git+https://gitlab.com/ase/ase
    - pip install git+https://gitlab.com/asr-dev/asr
    - pip install pytest boddle
    - pip install .
    - pytest -v --color=yes
  when: manual
